---
title: TPL - Forestry
tagline: Demo CMS with Forestry
description: The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme
  for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.
url: https://distracted-noyce-b53c06.netlify.com
baseurl: ''
author:
  name: Charlene Wang
  url: ''
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#06749C"
  sidebar-fg-color: "#003E6B"
  link-color: "#9DDCE1"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
markdown: ''
highlighter: ''
